# Copyright 2026 The Confii Contributors
# SPDX-License-Identifier: MIT
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /loader/cloud
      - /secret/cloud
      - /examples/cloud
      - /tools/security-insights-check
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
    open-pull-requests-limit: 5
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      routine-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
    open-pull-requests-limit: 5
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      routine-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /tools/fuzz-introspector
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
    open-pull-requests-limit: 2
