default_environment: development
env_switcher: APP_ENV
env_prefix: APP
deep_merge: true
use_env_expander: true
validate_on_load: false
environment_strategy: named_files
sources:
  - type: environment_files
    search_paths: [config]
    default_file: default.yaml
    environment_file: "{environment}.yaml"
    default_required: true
    environment_required: true
